---
language: go

go_import_path: github.com/dolmen-go/openapi-preprocessor

go:
- 1.13.x
- tip
- 1.12.x
- 1.11.x
- 1.10.x

sudo: false

before_install:
- go get -t -v ./...

script:
- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
